run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - gofmt
    - revive
    - goimports

issues:
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true
  revive:
    ignore-generated-header: true
